server:
  port: 80
  servlet:
    session:
      timeout: 3600
  compression:
    enabled: true
  mime-types: text/javascript,application/javascript,text/css

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/blogspot?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true

mybatis:
  mapper-locations: classpath:/mybatis/*.xml